### ISSUE TITLE
bug/Notion Connector Issue: ModuleNotFoundError for 'unstructured.ingest.connector.notion.types'

### ISSUE THREAD

**Issue by eremeye** [Unstructured-IO/unstructured#1095]
**Description:** 

While using unstructured version 0.9.2 and running the notion connector with the following command:

```bash
unstructured-ingest \                      
    notion \
    --api-key "*******" \
    --structured-output-dir notion-ingest-output \
    --page-ids "*******" \
    --num-processes 2 \
    --verbose
```

I received the following error:

```bash
2023-08-11 11:08:52,821 MainProcess ERROR    No module named 'unstructured.ingest.connector.notion.types'
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/unstructured/ingest/cli/cmds/notion.py", line 41, in notion
    notion_fn(connector_config=connector_config, processor_config=processor_config, **options)
  File "/.venv/lib/python3.11/site-packages/unstructured/ingest/runner/notion.py", line 45, in notion
    from unstructured.ingest.connector.notion.connector import (
  File "/.venv/lib/python3.11/site-packages/unstructured/ingest/connector/notion/connector.py", line 8, in <module>
    from unstructured.ingest.connector.notion.types.database import Database
ModuleNotFoundError: No module named 'unstructured.ingest.connector.notion.types'
Error: No module named 'unstructured.ingest.connector.notion.types'
```

### Environment Details:
- **unstructured version:** 0.9.2
- **Python Version:** 3.11
- **Operating System:** Mac OS 12.5.1

**Comment by rbiseck3** [comment]
FIx in review: [roman/notion module not found fix](https://github.com/Unstructured-IO/unstructured/pull/1100)

**Comment by cragwolfe** [comment]
fix is now in main and will be in the next Unstructured release
