### ISSUE TITLE
bug/Out of memory in xml parsing

### ISSUE THREAD

**Issue by slavag** [Unstructured-IO/unstructured#1236]
**Describe the bug**
Trying to parse XML (large 1.1GB) and getting "out of memory" exception
**To Reproduce**
To parse large XML

**Environment Info**
OS version:  macOS-13.5-arm64-arm-64bit
Python version:  3.11.3
unstructured version:  0.9.0
unstructured-inference version:  0.5.7
pytesseract version:  0.3.10
Torch version:  2.1.0.dev20230811
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version: file-5.41

**Additional context**
```
Failed to ingest /Users/slava/Documents/Development/private/AI/cloud-20230805/tickets.xml due to Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 2005, in path_to_doc1
    res = file_to_doc(file, base_path=None, verbose=verbose, fail_any_exception=fail_any_exception,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 1894, in file_to_doc
    doc1 = loader.load()
           ^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/xml.py", line 42, in _get_elements
    return partition_xml(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/documents/elements.py", line 222, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 628, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/partition/xml.py", line 105, in partition_xml
    raw_text = get_leaf_elements(filename=filename, file=file, xml_path=xml_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/partition/xml.py", line 40, in get_leaf_elements
    root = ET.fromstring(raw_text)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: out of memory: line 1, column 0
```

**Comment by qued** [comment]
Hi @slavag ! Thanks for opening an issue, we're looking into this. Is there any chance you could share the file that caused the OOM?

**Comment by slavag** [comment]
@qued Hi, unfortunately no, it's contains sensitive data.
