### ISSUE TITLE
bug/UnboundLocalError: isalnum when parsing PDF 

### ISSUE THREAD

**Issue by jasonchester** [Unstructured-IO/unstructured#1623]
**Describe the bug**
When parsing attached pdf, error is thrown:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[/Users/jason.chester/unstructured_issue/unstructured_experiment.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/unstructured_experiment.ipynb) Cell 2 line 2
      [1](vscode-notebook-cell:/Users/jason.chester/unstructured_issue/unstructured_experiment.ipynb#W1sZmlsZQ%3D%3D?line=0) from unstructured.partition.pdf import partition_pdf
----> [2](vscode-notebook-cell:/Users/jason.chester/unstructured_issue/unstructured_experiment.ipynb#W1sZmlsZQ%3D%3D?line=1) elements = partition_pdf("unstructured-pdf-issue.pdf")

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/documents/elements.py:276](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/documents/elements.py:276), in process_metadata.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    274 @functools.wraps(func)
    275 def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> List[Element]:
--> 276     elements = func(*args, **kwargs)
    277     sig = inspect.signature(func)
    278     params: Dict[str, Any] = dict(**dict(zip(sig.parameters, args)), **kwargs)

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/file_utils/filetype.py:551](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/file_utils/filetype.py:551), in add_metadata_with_filetype.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    549 @functools.wraps(func)
    550 def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> List[Element]:
--> 551     elements = func(*args, **kwargs)
    552     sig = inspect.signature(func)
    553     params: Dict[str, Any] = dict(**dict(zip(sig.parameters, args)), **kwargs)

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/chunking/title.py:211](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/chunking/title.py:211), in add_chunking_strategy.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    209 @functools.wraps(func)
    210 def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> List[Element]:
--> 211     elements = func(*args, **kwargs)
    212     sig = inspect.signature(func)
    213     params: Dict[str, Any] = dict(**dict(zip(sig.parameters, args)), **kwargs)

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:148](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:148), in partition_pdf(filename, file, include_page_breaks, strategy, infer_table_structure, ocr_languages, languages, max_partition, min_partition, include_metadata, metadata_filename, metadata_last_modified, chunking_strategy, links, **kwargs)
    142         languages = convert_old_ocr_languages_to_languages(ocr_languages)
    143         logger.warning(
    144             "The ocr_languages kwarg will be deprecated in a future version of unstructured. "
    145             "Please use languages instead.",
    146         )
--> 148 return partition_pdf_or_image(
    149     filename=filename,
    150     file=file,
    151     include_page_breaks=include_page_breaks,
    152     strategy=strategy,
    153     infer_table_structure=infer_table_structure,
    154     languages=languages,
    155     max_partition=max_partition,
    156     min_partition=min_partition,
    157     metadata_last_modified=metadata_last_modified,
    158     **kwargs,
    159 )

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:245](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:245), in partition_pdf_or_image(filename, file, is_image, include_page_breaks, strategy, infer_table_structure, ocr_languages, languages, max_partition, min_partition, metadata_last_modified, **kwargs)
    229 last_modification_date = get_the_last_modification_date_pdf_or_img(
    230     file=file,
    231     filename=filename,
    232 )
    234 if (
    235     not is_image
    236     and determine_pdf_or_image_strategy(
   (...)
    243     != "ocr_only"
    244 ):
--> 245     extracted_elements = extractable_elements(
    246         filename=filename,
    247         file=spooled_to_bytes_io_if_needed(file),
    248         include_page_breaks=include_page_breaks,
    249         metadata_last_modified=metadata_last_modified or last_modification_date,
    250         **kwargs,
    251     )
    252     pdf_text_extractable = any(
    253         isinstance(el, Text) and el.text.strip() for el in extracted_elements
    254     )
    255 else:

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:171](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:171), in extractable_elements(filename, file, include_page_breaks, metadata_last_modified, **kwargs)
    169 if isinstance(file, bytes):
    170     file = io.BytesIO(file)
--> 171 return _partition_pdf_with_pdfminer(
    172     filename=filename,
    173     file=file,
    174     include_page_breaks=include_page_breaks,
    175     metadata_last_modified=metadata_last_modified,
    176     **kwargs,
    177 )

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/utils.py:159](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/utils.py:159), in requires_dependencies.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    150 if len(missing_deps) > 0:
    151     raise ImportError(
    152         f"Following dependencies are missing: {', '.join(missing_deps)}. "
    153         + (
   (...)
    157         ),
    158     )
--> 159 return func(*args, **kwargs)

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:423](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:423), in _partition_pdf_with_pdfminer(filename, file, include_page_breaks, metadata_last_modified, **kwargs)
    421     with open_filename(filename, "rb") as fp:
    422         fp = cast(BinaryIO, fp)
--> 423         elements = _process_pdfminer_pages(
    424             fp=fp,
    425             filename=filename,
    426             include_page_breaks=include_page_breaks,
    427             metadata_last_modified=metadata_last_modified,
    428             **kwargs,
    429         )
    431 elif file:
    432     fp = cast(BinaryIO, file)

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:507](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:507), in _process_pdfminer_pages(fp, filename, include_page_breaks, metadata_last_modified, **kwargs)
    501 if len(annotation_list) > 0 and isinstance(obj, LTTextBox):
    502     annotations_within_element = check_annotations_within_element(
    503         annotation_list,
    504         bbox,
    505         i + 1,
    506     )
--> 507     _, words = get_word_bounding_box_from_element(obj, height)
    508     for annot in annotations_within_element:
    509         urls_metadata.append(map_bbox_and_index(words, annot))

File [~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:1004](https://file+.vscode-resource.vscode-cdn.net/Users/jason.chester/unstructured_issue/~/unstructured_issue/.venv/lib/python3.11/site-packages/unstructured/partition/pdf.py:1004), in get_word_bounding_box_from_element(obj, height)
   1001 if index == 0:
   1002     isalnum = char.isalnum()
-> 1004 if char.isalnum() != isalnum:
   1005     isalnum = char.isalnum()
   1006     words.append(
   1007         {"text": word, "bbox": (x1, y1, x2, y2), "start_index": start_index},
   1008     )

UnboundLocalError: cannot access local variable 'isalnum' where it is not associated with a value
```

**To Reproduce**

with pdf: 
[unstructured-pdf-issue.pdf](https://github.com/Unstructured-IO/unstructured/files/12793777/unstructured-pdf-issue.pdf)

```python
from unstructured.partition.pdf import partition_pdf
elements = partition_pdf("unstructured-pdf-issue.pdf")
```

**Expected behavior**
Error should not be thrown.

**Screenshots**

**Environment Info**
```
python ./collect_env.py 
/Users/jason.chester/unstructured_issue/./collect_env.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
OS version:  macOS-12.7-x86_64-i386-64bit
Python version:  3.11.5
unstructured version:  0.10.18
unstructured-inference version:  0.5.31
pytesseract version:  0.3.10
Torch version:  2.0.1
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
Traceback (most recent call last):
  File "/Users/jason.chester/unstructured_issue/./collect_env.py", line 242, in <module>
    main()
  File "/Users/jason.chester/unstructured_issue/./collect_env.py", line 234, in main
    libreoffice_version = get_libreoffice_version()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jason.chester/unstructured_issue/./collect_env.py", line 163, in get_libreoffice_version
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice'
```

**Comment by Klaijan** [comment]
The error is fixed and waiting to be released real soon! Thanks for your report!

**Comment by ahmetmeleq** [comment]
Follow at: #1584
