### ISSUE TITLE
bug/division-by-zero-in-pdf-parition

### ISSUE THREAD

**Issue by badGarnet** [Unstructured-IO/unstructured#1699]
**Describe the bug**
```
2023-10-10 08:39:21,892 MainProcess ERROR    Error in partitioning content: float division by zero
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/yaoyou/develop/unstructured/unstructured/ingest/error.py", line 19, in wrapper
    return f(*args, **kwargs)
  File "/Users/yaoyou/develop/unstructured/unstructured/ingest/interfaces.py", line 261, in partition_file
    elements = partition(
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/auto.py", line 316, in partition
    elements = _partition_pdf(
  File "/Users/yaoyou/develop/unstructured/unstructured/documents/elements.py", line 294, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/yaoyou/develop/unstructured/unstructured/file_utils/filetype.py", line 551, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/yaoyou/develop/unstructured/unstructured/chunking/title.py", line 277, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/pdf.py", line 155, in partition_pdf
    return partition_pdf_or_image(
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/pdf.py", line 252, in partition_pdf_or_image
    extracted_elements = extractable_elements(
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/pdf.py", line 178, in extractable_elements
    return _partition_pdf_with_pdfminer(
  File "/Users/yaoyou/develop/unstructured/unstructured/utils.py", line 159, in wrapper
    return func(*args, **kwargs)
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/pdf.py", line 463, in _partition_pdf_with_pdfminer
    elements = _process_pdfminer_pages(
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/pdf.py", line 542, in _process_pdfminer_pages
    annotations_within_element = check_annotations_within_element(
  File "/Users/yaoyou/develop/unstructured/unstructured/partition/pdf.py", line 1100, in check_annotations_within_element
    calculate_intersection_area(element_bbox, annotation["bbox"])
ZeroDivisionError: float division by zero
```
the line in question: https://github.com/Unstructured-IO/unstructured/blob/dcd6d0ff67b79739da2578db0c5379f4e2338354/unstructured/partition/pdf.py#L1100-L1101

**To Reproduce**
[DEMO-sex_based_diff_parkisons.pdf](https://github.com/Unstructured-IO/unstructured/files/12858986/DEMO-sex_based_diff_parkisons.pdf)
use the file here and hi_res strategy

**Expected behavior**

either:
- box with area 0 shouldn't be considered in this step
- box with area 0 do not overlap with any other box

**Comment by badGarnet** [comment]
duplicate of #1663
