### ISSUE TITLE
bug/gdrive ModuleNotFoundError: No module named 'unstructured.ingest.pipeline.reformat'

### ISSUE THREAD

**Issue by l4b4r4b4b4** [Unstructured-IO/unstructured#1724]
**Describe the bug**  
When running the provided code snippet, the application throws a `ModuleNotFoundError` stating that it cannot find the module 'unstructured.ingest.pipeline.reformat'.  
   
**To Reproduce**  
The error can be reproduced by running the following code:  
   
```python  
from unstructured.ingest.interfaces import PartitionConfig, ReadConfig  
from unstructured.ingest.runner.google_drive import gdrive  
gdrive(  
    verbose=True,  
    read_config=ReadConfig(preserve_downloads=True, download_dir=str(  
        f"/ingest/files/projects/{project_id}/datasets/{session_id}/gdrives/{gdrive_id}"  
    )),  
    partition_config=PartitionConfig(  
        output_dir=str(  
            f"/ingest/data/projects/{project_id}/datasets/{session_id}/gdrives/{gdrive_id}"  
        ),  
        num_processes=config.ingest_batch_size,  
        pdf_infer_table_structure=True  
    ),  
    drive_id=gdrive_id,  
    service_account_key="/app/app/data/keys/dev-service-account-key.json",  
    recursive=True,  
)  
```  
   
**Expected behavior**  
The expected behavior is that the application should be able to import the necessary modules and successfully execute the `gdrive` function.  
   
**Environment Info**  
Please run `python scripts/collect_env.py` and paste the output here. This will help us understand more about the environment in which the bug occurred.  
   
**Additional context**  
It appears that there might be a mistake in the module path, or the specified module does not exist in the project or installed packages. Please check the installed packages and the project structure to ensure that the path 'unstructured.ingest.pipeline.reformat' is correct.

**Comment by ryannikolaidis** [comment]
Thanks for the report! Fix in progress [here](https://github.com/Unstructured-IO/unstructured/pull/1717)

**Comment by awalker4** [comment]
The fix is released! Please update to 0.10.22.

**Comment by homanp** [comment]
@awalker4 This is still an issue in `v0.12.4`. 

```
INFO:     Started reloader process [9800] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ismailpelaseyed/Projects/super-rag/.venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/ismailpelaseyed/Projects/super-rag/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/super-rag/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/Users/ismailpelaseyed/Projects/super-rag/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/super-rag/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/ismailpelaseyed/Projects/super-rag/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ismailpelaseyed/Projects/super-rag/main.py", line 6, in <module>
    from router import router
  File "/Users/ismailpelaseyed/Projects/super-rag/router.py", line 3, in <module>
    from api import delete, ingest, query
  File "/Users/ismailpelaseyed/Projects/super-rag/api/ingest.py", line 9, in <module>
    from service.ingest import handle_urls, handle_google_drive
  File "/Users/ismailpelaseyed/Projects/super-rag/service/ingest.py", line 4, in <module>
    from unstructured.ingest.connector.google_drive import (
ModuleNotFoundError: No module named 'unstructured.ingest'
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
```

**Comment by ryannikolaidis** [comment]
hi @homanp, I'm not actually able to reproduce this issue on my end. Updated the original code example and it ran just fine. Can you share the version of Unstructured on which you're working and a code sample? (edited)

**Comment by homanp** [comment]
> hi @homanp, I'm not actually able to reproduce this issue on my end. Updated the original code example and it ran just fine. Can you share the version of Unstructured on which you're working and a code sample? (edited)

Hey, `v0.12.4`, installed `unstructured[google-drive]`. Using the code sample in your docs.
