### ISSUE TITLE
bug: ingest CLI fails if any document fails to partition

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#1734]
**Describe the bug**
Currently if a `unstructured.ingest.error.PartitionError` occurs when processing _any_ IngestDoc being handled by the ingest pipeline, the entire ingest request fails.

**To Reproduce**
Add a filetype that is not supported to a batch that is ingested. This will trigger `unstructured.ingest.error.PartitionError`. Note that   processing stops on the error and the rest of the partitioned files are never copied to the final destination.

**Expected behavior**
The error should be logged, but all other processable documents should be processed through completion.

**Screenshots**
```

2023-10-12 10:12:55,665 SpawnPoolWorker-16 INFO     writing partitioned content to /Users/ryannikolaidis/.cache/unstructured/ingest/pipeline/partitioned/8b3d9684badee3984417e954e5b2c578.json
2023-10-12 10:12:56,148 MainProcess ERROR    Error in partitioning content: Invalid file /tmp/eval/download/src/.DS_Store. The FileType.UNK file type is not supported in partition.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/error.py", line 19, in wrapper
    return f(*args, **kwargs)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/interfaces.py", line 261, in partition_file
    elements = partition(
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/partition/auto.py", line 461, in partition
    raise ValueError(f"{msg}. The {filetype} file type is not supported in partition.")
ValueError: Invalid file /tmp/eval/download/src/.DS_Store. The FileType.UNK file type is not supported in partition.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/error.py", line 19, in wrapper
    return f(*args, **kwargs)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/pipeline/partition.py", line 33, in run
    elements = doc.process_file(
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/interfaces.py", line 305, in process_file
    isd_elems_raw = self.partition_file(partition_config=partition_config, **partition_kwargs)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/error.py", line 22, in wrapper
    raise cls(cls.error_string.format(str(error))) from error
unstructured.ingest.error.PartitionError: Error in partitioning content: Invalid file /tmp/eval/download/src/.DS_Store. The FileType.UNK file type is not supported in partition.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/cli/cmds/s3.py", line 64, in s3_source
    s3_runner.run(**options)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/runner/s3.py", line 42, in run
    self.process_documents(
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/runner/base_runner.py", line 40, in process_documents
    process_documents(
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/processor.py", line 75, in process_documents
    pipeline.run()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/pipeline/pipeline.py", line 57, in run
    partitioned_jsons = self.partition_node(iterable=json_docs)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/pipeline/interfaces.py", line 69, in __call__
    self.result = pool.map(self.run, iterable)
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
unstructured.ingest.error.PartitionError: Error in partitioning content: Invalid file /tmp/eval/download/src/.DS_Store. The FileType.UNK file type is not supported in partition.
Error: Error in partitioning content: Invalid file /tmp/eval/download/src/.DS_Store. The FileType.UNK file type is not supported in partition.
```

**Environment Info**
OS version:  macOS-13.4.1-arm64-arm-64bit
Python version:  3.10.11
unstructured version:  0.10.17.dev16
unstructured-inference version:  0.6.6
pytesseract version:  0.3.10
Torch version:  2.0.1
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.0

**Additional context**
Discovered with s3 connector (though presumably this should be true for any connector)

**Comment by ryannikolaidis** [comment]
cc @rbiseck3

**Comment by ahmetmeleq** [comment]
Can we solve this via implementing a custom wrap method here that doesn't raise and rather log?
https://github.com/Unstructured-IO/unstructured/blob/9b5d5e0f9e552e57250f6e16bc0e6fb60ff4dc76/unstructured/ingest/error.py#L44-L45

**Comment by rbiseck3** [comment]
Fixed in this PR: https://github.com/Unstructured-IO/unstructured/pull/1736
