### ISSUE TITLE
bug/pdf links sometimes break

### ISSUE THREAD

**Issue by HenryL27** [Unstructured-IO/unstructured#1854]
**Describe the bug**
Some hyperlinks in pdfs point to pages in other pdfs, or similarly odd places. This breaks the parsing because the uri that gets added to the element is only initialized in a couple of cases.

**To Reproduce**
use this [battery charging manual](https://www.sram.com/globalassets/document-hierarchy/user-manuals/sram-road/electronic/battery-and-charger-user-manual.pdf)
```
>>> from unstructured.partition.auto import partition
>>> partition('/Users/hmlin/Downloads/battery-and-charger-user-manual.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/auto.py", line 316, in partition
    elements = _partition_pdf(
               ^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/documents/elements.py", line 280, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 551, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/chunking/title.py", line 257, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 155, in partition_pdf
    return partition_pdf_or_image(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 252, in partition_pdf_or_image
    extracted_elements = extractable_elements(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 178, in extractable_elements
    return _partition_pdf_with_pdfminer(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/utils.py", line 159, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 430, in _partition_pdf_with_pdfminer
    elements = _process_pdfminer_pages(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 500, in _process_pdfminer_pages
    annotation_list = get_uris(page.annots, height, coordinate_system, i + 1)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 893, in get_uris
    return get_uris_from_annots(annots.resolve(), height, coordinate_system, page_number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 946, in get_uris_from_annots
    "uri": uri,
           ^^^
UnboundLocalError: cannot access local variable 'uri' where it is not associated with a value
```

**Expected behavior**
This should not crash. If the hyperlink is an unexpected format, then ignore it

**Screenshots**

**Environment Info**
```
OS version:  macOS-14.0-arm64-arm-64bit
Python version:  3.11.2
unstructured version:  0.10.19
unstructured-inference version:  0.2.4
pytesseract version:  0.3.10
Torch version:  2.0.0
Detectron2 version:  0.6
DEPRECATION: Loading egg at /Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sentencepiece-0.1.98-py3.11-macosx-13.0-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sentencepiece-0.1.98-py3.11-macosx-13.0-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
PaddleOCR is not installed
Libmagic version: file-5.41
magic file from /usr/share/file/magic
Traceback (most recent call last):
  File "/Users/hmlin/Aryn/unstructured/scripts/collect_env.py", line 242, in <module>
    main()
  File "/Users/hmlin/Aryn/unstructured/scripts/collect_env.py", line 234, in main
    libreoffice_version = get_libreoffice_version()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/Aryn/unstructured/scripts/collect_env.py", line 163, in get_libreoffice_version
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/hmlin/.pyenv/versions/3.11.2/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice'
```

**Additional context**

**Comment by Klaijan** [comment]
Hi @HenryL27! Thank you for reporting. However, I am unable to reproduce the error with the given pdf file. Would you mind providing more pdf files as a context. Meanwhile, I see you are on unstructured version 0.10.19. It might worth trying to pull our latest release 0.10.25 and try again.
