### ISSUE TITLE
bug: SharePoint permissions fetching should be opt-in

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#1891]
**Describe the bug**
I running the SharePoint connector from the cli without specifying any permissions options, but getting an error about not being able to obtain the permissions token

**To Reproduce**
Run SharePoint connector without permissions options:

```
PYTHONPATH=. ./unstructured/ingest/main.py \
  sharepoint \
  --download-dir /tmp/sharepoint-demo/download \
  --num-processes 6 \
  --strategy fast \
  --preserve-downloads \
  --reprocess \
  --output-dir /tmp/sharepoint-demo/result \
  --verbose \
  --client-cred "$SHAREPOINT_CRED" \
  --client-id "$SHAREPOINT_CLIENT_ID" \
  --site "$SHAREPOINT_SITE" \
  --path "Shared Documents" \
  --recursive
```

**Expected behavior**
Permission fetching should not be attempted.

**Screenshots**
```
  --recursive
2023-10-26 08:40:20,854 MainProcess DEBUG    options: {'download_dir': '/tmp/sharepoint-demo/download', 'num_processes': 6, 'strategy': 'fast', 'preserve_downloads': True, 'reprocess': True, 'output_dir': '/tmp/sharepoint-demo/result', 'verbose': True, 'client_cred': '*******', 'client_id': '*******', 'site': 'https://030rx-admin.sharepoint.com/', 'path': 'Shared Documents', 'recursive': True, 'skip_infer_table_types': None, 'pdf_infer_table_structure': False, 'ocr_languages': None, 'encoding': None, 'fields_include': ['element_id', 'text', 'type', 'metadata', 'embeddings'], 'flatten_metadata': False, 'metadata_include': [], 'metadata_exclude': [], 'partition_by_api': False, 'partition_endpoint': 'https://api.unstructured.io/general/v0/general', 'api_key': None, 're_download': False, 'download_only': False, 'max_docs': None, 'embedding_api_key': None, 'embedding_model_name': None, 'chunk_elements': False, 'chunk_multipage_sections': False, 'chunk_combine_under_n_chars': 500, 'chunk_new_after_n_chars': 1500, 'work_dir': '/Users/ryannikolaidis/.cache/unstructured/ingest/pipeline', 'raise_on_error': False, 'permissions_application_id': None, 'permissions_client_cred': None, 'permissions_tenant': None, 'max_retries': None, 'max_retry_time': None, 'files_only': False}
2023-10-26 08:40:20,856 MainProcess INFO     running pipeline: DocFactory -> Reader -> Partitioner -> Copier with config: {"reprocess": true, "verbose": true, "work_dir": "/Users/ryannikolaidis/.cache/unstructured/ingest/pipeline", "output_dir": "/tmp/sharepoint-demo/result", "num_processes": 6, "raise_on_error": false}
2023-10-26 08:40:22,368 MainProcess INFO     Running doc factory to generate ingest docs. Source connector: {"processor_config": {"reprocess": true, "verbose": true, "work_dir": "/Users/ryannikolaidis/.cache/unstructured/ingest/pipeline", "output_dir": "/tmp/sharepoint-demo/result", "num_processes": 6, "raise_on_error": false}, "read_config": {"download_dir": "/tmp/sharepoint-demo/download", "re_download": false, "preserve_downloads": true, "download_only": false, "max_docs": null}, "connector_config": {"client_id": "8ed640cc-c6de-4ff1-8c18-2abcecb1e547", "client_credential": "b+OfndJ4wrirwOOi3eT4/9F+dto2sGsCmj7X8CvWRJ4=", "site_url": "https://030rx-admin.sharepoint.com/", "path": "Shared Documents", "process_pages": true, "recursive": true, "permissions_config": {"application_id": null, "client_cred": null, "tenant": null}}}
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/connector/sharepoint.py", line 66, in get_permissions_client
    permissions_connector = SharepointPermissionsConnector(self.permissions_config)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/connector/sharepoint.py", line 398, in __init__
    self.initialize()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/connector/sharepoint.py", line 401, in initialize
    self.access_token: str = self.get_access_token()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/utils.py", line 179, in wrapper
    return func(*args, **kwargs)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/connector/sharepoint.py", line 418, in get_access_token
    return response.json()["access_token"]
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/Users/ryannikolaidis/.pyenv/versions/3.10.11/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/./unstructured/ingest/main.py", line 11, in <module>
    main()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/./unstructured/ingest/main.py", line 7, in main
    ingest_cmd()
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ryannikolaidis/.pyenv/versions/unstructured/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/cli/base/src.py", line 41, in src
    runner.run(**options)
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/runner/sharepoint.py", line 63, in run
    self.process_documents(
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/runner/base_runner.py", line 57, in process_documents
    process_documents(
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/processor.py", line 86, in process_documents
    pipeline.run()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/pipeline/pipeline.py", line 51, in run
    json_docs = self.doc_factory_node()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/pipeline/interfaces.py", line 66, in __call__
    self.result = self.run()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/pipeline/doc_factory.py", line 10, in run
    docs = self.source_doc_connector.get_ingest_docs()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/connector/sharepoint.py", line 377, in get_ingest_docs
    permissions_client = self.connector_config.get_permissions_client()
  File "/Users/ryannikolaidis/Development/unstructured/unstructured/unstructured/ingest/connector/sharepoint.py", line 70, in get_permissions_client
    logger.error("Couldn't obtain Sharepoint permissions ingestion access token:", e)
Message: "Couldn't obtain Sharepoint permissions ingestion access token:"
Arguments: (KeyError('access_token'),)
```

**Environment Info**
NA

**Additional context**
None

**Comment by ahmetmeleq** [comment]
Came up to this in #1774 and had a quick fix already

Also adding opt-in functionality now 👍
