### ISSUE TITLE
bug: PDF partitioning failure: KeyError: 'N'

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#2059]
**Describe the bug**

[google-2023-environmental-report_condensed.pdf](https://github.com/Unstructured-IO/unstructured/files/13329418/google-2023-environmental-report_condensed.pdf) causes a partition error.

**To Reproduce**

    elements = partition(filename="google-2023-environmental-report_condensed.pdf", strategy="fast")

**Environment Info**
unstructured version: 0.10.30

**Additional context**

This issue was originally raised in [this slack thread](https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1699828457949919).

Full trace:

Traceback (most recent call last):
  File "test-partition-simple.py", line 32, in <module>
    elements = partition(filename=filename, strategy=strategy)
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/auto.py", line 383, in partition
    elements = _partition_pdf(
  File "/Users/cragwolfe/r/unstructured/unstructured/documents/elements.py", line 371, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/cragwolfe/r/unstructured/unstructured/file_utils/filetype.py", line 591, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/cragwolfe/r/unstructured/unstructured/file_utils/filetype.py", line 546, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/cragwolfe/r/unstructured/unstructured/chunking/title.py", line 297, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/pdf.py", line 183, in partition_pdf
    return partition_pdf_or_image(
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/pdf.py", line 288, in partition_pdf_or_image
    extracted_elements = extractable_elements(
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/pdf.py", line 206, in extractable_elements
    return _partition_pdf_with_pdfminer(
  File "/Users/cragwolfe/r/unstructured/unstructured/utils.py", line 179, in wrapper
    return func(*args, **kwargs)
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/pdf.py", line 515, in _partition_pdf_with_pdfminer
    elements = _process_pdfminer_pages(
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/pdf.py", line 572, in _process_pdfminer_pages
    interpreter.process_page(page)
  File "/Users/cragwolfe/.pyenv/versions/unst/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 997, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/cragwolfe/.pyenv/versions/unst/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 1014, in render_contents
    self.init_resources(resources)
  File "/Users/cragwolfe/.pyenv/versions/unst/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 387, in init_resources
    colorspace = get_colorspace(resolve1(spec))
  File "/Users/cragwolfe/.pyenv/versions/unst/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 370, in get_colorspace
    return PDFColorSpace(name, stream_value(spec[1])["N"])
  File "/Users/cragwolfe/.pyenv/versions/unst/lib/python3.8/site-packages/pdfminer/pdftypes.py", line 285, in __getitem__
    return self.attrs[name]
KeyError: 'N'

**Comment by awalker4** [comment]
The error happens [here](https://github.com/pdfminer/pdfminer.six/blob/5114acdda61205009221ce4ebf2c68c144fc4ee5/pdfminer/pdfinterp.py#L364C9-L374C55):

```
def get_colorspace(spec: object) -> Optional[PDFColorSpace]:
            if isinstance(spec, list):
                name = literal_name(spec[0])
            else:
                name = literal_name(spec)
            if name == "ICCBased" and isinstance(spec, list) and 2 <= len(spec):
                return PDFColorSpace(name, stream_value(spec[1])["N"])
            elif name == "DeviceN" and isinstance(spec, list) and 2 <= len(spec):
                return PDFColorSpace(name, len(list_value(spec[1])))
            else:
                return PREDEFINED_COLORSPACE.get(name)
```

When a pdf uses an ICC profile for its color space, it expects a value N for the number of color channels ([source](https://blog.idrsolutions.com/what-are-iccbased-colorspaces-in-pdf-files/)). When we open the raw pdf we can see that the file comes from PyPDF, which may have a bug. Further down, we can see that the ICC section does not have N.

```
/Producer (PyPDF2)
...
...
[ /ICCBased 67 0 R ]
endobj
67 0 obj
<<
/Filter /FlateDecode
/Length 2583
>>
```

For a workaround, I tried removing the colorspace info from `pdf.resources` so we skip this code. This does change the stack - we skip over the error, but we hit it later when the `resources` object is reloaded from the data. For this to work we need to be able to remove the colorprofile and then save the page back into the pdf stream.

([Source](https://github.com/Unstructured-IO/unstructured/blob/b11c5467572ed8cab121cc021dba061b9f49e13c/unstructured/partition/pdf.py#L571))
```
    for i, page in enumerate(PDFPage.get_pages(fp)):  # type: ignore
        print(page.contents)
        if "ColorSpace" in page.resources:
            del page.resources["ColorSpace"]

```

**Comment by awalker4** [comment]
Will keep exploring a workaround while we submit a fix to pdfminer.

**Comment by awalker4** [comment]
Workaround is to drop the color profile inside of pdfminer. As per my last comment, we can't do it on the page itself because the `resources` map is reloaded elsewhere. This gives us a response for the affected pdf:

```
@wrapt.patch_function_wrapper('pdfminer.pdfinterp', 'PDFPageInterpreter.init_resources')
def pdfminer_interpreter_init_resources(wrapped, instance, args, kwargs):
    resources = args[0]
    if "ColorSpace" in resources:
        del resources["ColorSpace"]

    return wrapped(resources)
```
