### ISSUE TITLE
bug/partition_pdf auto strategy gives "invalid length" error

### ISSUE THREAD

**Issue by Klaijan** [Unstructured-IO/unstructured#2084]
**Describe the bug**
`partition_pdf` using `strategy="auto"` gives "invalid length" error, but `strategy="ocr_only"` works fine.

**To Reproduce**
partition_pdf(filename="label-party/holistic-src/NASA-SNA-8-D-027III-Rev2-CsmLmSpacecraftOperationalDataBook-Volume3-MassProperties-pg856.pdf")

**Expected behavior**
Expected to be partitioning smoothly, and/or falls to alternative strategy if the first strategy doesn't work.

**Screenshots**
```
>>> partition_pdf(filename="label-party/holistic-src/NASA-SNA-8-D-027III-Rev2-CsmLmSpacecraftOperationalDataBook-Volume3-MassProperties-pg856.pdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/documents/elements.py", line 371, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/file_utils/filetype.py", line 591, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/file_utils/filetype.py", line 546, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/chunking/title.py", line 297, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/pdf.py", line 171, in partition_pdf
    return partition_pdf_or_image(
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/pdf.py", line 248, in partition_pdf_or_image
    extracted_elements = extractable_elements(
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/pdf.py", line 195, in extractable_elements
    return _partition_pdf_with_pdfminer(
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/utils.py", line 179, in wrapper
    return func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/pdf.py", line 483, in _partition_pdf_with_pdfminer
    elements = _process_pdfminer_pages(
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/pdf.py", line 556, in _process_pdfminer_pages
    interpreter.process_page(page)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 997, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 1014, in render_contents
    self.init_resources(resources)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/pdf.py", line 535, in pdfminer_interpreter_init_resources
    return wrapped(resources)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 384, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 234, in get_font
    font = self.get_font(None, subspec)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 225, in get_font
    font = PDFCIDFont(self, spec)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/pdffont.py", line 1078, in __init__
    CMapParser(self.unicode_map, BytesIO(strm.get_data())).run()
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/cmapdb.py", line 294, in run
    self.nextobject()
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/psparser.py", line 656, in nextobject
    self.do_keyword(pos, token)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/cmapdb.py", line 454, in do_keyword
    self.cmap.add_cid2unichr(nunpack(cid), code)
  File "/Users/klaijan/.pyenv/versions/unstructured/lib/python3.8/site-packages/pdfminer/utils.py", line 363, in nunpack
    raise TypeError("invalid length: %d" % length)
TypeError: invalid length: 6
```

**Environment Info**
```
OS version:  macOS-13.4-arm64-arm-64bit
Python version:  3.8.15
unstructured version:  0.8.1
unstructured-inference version:  0.7.10
pytesseract version:  0.3.10
Torch version:  2.1.0
Detectron2 is not installed

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.2
```

**Additional context**

**Comment by christinestraub** [comment]
@Klaijan Can you please share the pdf file (`NASA-SNA-8-D-027III-Rev2-CsmLmSpacecraftOperationalDataBook-Volume3-MassProperties-pg856.pdf`)?

**Comment by Klaijan** [comment]
[NASA-SNA-8-D-027III-Rev2-CsmLmSpacecraftOperationalDataBook-Volume3-MassProperties-pg856.pdf](https://github.com/Unstructured-IO/unstructured/files/13372539/NASA-SNA-8-D-027III-Rev2-CsmLmSpacecraftOperationalDataBook-Volume3-MassProperties-pg856.pdf)

Here!

**Comment by christinestraub** [comment]
The error happens [here](https://github.com/pdfminer/pdfminer.six/blob/5114acdda61205009221ce4ebf2c68c144fc4ee5/pdfminer/pdfinterp.py#L199-L241):

```
def get_font(self, objid: object, spec: Mapping[str, object]) -> PDFFont:
    if objid and objid in self._cached_fonts:
        font = self._cached_fonts[objid]
    else:
        log.debug("get_font: create: objid=%r, spec=%r", objid, spec)
        if settings.STRICT:
            if spec["Type"] is not LITERAL_FONT:
                raise PDFFontError("Type is not /Font")
        # Create a Font object.
        if "Subtype" in spec:
            subtype = literal_name(spec["Subtype"])
        else:
            if settings.STRICT:
                raise PDFFontError("Font Subtype is not specified.")
            subtype = "Type1"
        if subtype in ("Type1", "MMType1"):
            # Type1 Font
            font = PDFType1Font(self, spec)
        elif subtype == "TrueType":
            # TrueType Font
            font = PDFTrueTypeFont(self, spec)
        elif subtype == "Type3":
            # Type3 Font
            font = PDFType3Font(self, spec)
        elif subtype in ("CIDFontType0", "CIDFontType2"):
            # CID Font
            font = PDFCIDFont(self, spec)
        elif subtype == "Type0":
            # Type0 Font
            dfonts = list_value(spec["DescendantFonts"])
            assert dfonts
            subspec = dict_value(dfonts[0]).copy()
            for k in ("Encoding", "ToUnicode"):
                if k in spec:
                    subspec[k] = resolve1(spec[k])
            font = self.get_font(None, subspec)
        else:
            if settings.STRICT:
                raise PDFFontError("Invalid Font spec: %r" % spec)
            font = PDFType1Font(self, spec)  # this is so wrong!
        if objid and self.caching:
            self._cached_fonts[objid] = font
    return font
```

This issue is similar to #2059, but in this case, we can't just drop the font info from `pdf.resources` because it affects the text extraction. For a workaround, I tried to add exception handling to handle unexpected errors when extracting pdf text and to help determine pdf strategy.

**Comment by cragwolfe** [comment]
@christinestraub , does it seem reasonable to submit an upstream patch here?

**Comment by cragwolfe** [comment]
reference: a recent pdfminer workaround that was added: https://github.com/Unstructured-IO/unstructured/commit/2931cb38e8a5159e9c790a314b848c5c3ff58bb4

**Comment by christinestraub** [comment]
@cragwolfe I already tried the recent pdfminer workaround but in this case, we can't just drop the font info from `pdf.resources` because it affects the text extraction. When I tried to remove the font info from `pdf.resources`, the text extraction was broken (very poor).
