### ISSUE TITLE
bug/unstructured-ingest --help throws an error on missing httpx module

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#2112]
$ unstructured-ingest --help
Traceback (most recent call last):
  File "/Users/cragwolfe/.pyenv/versions/unstlib/bin/unstructured-ingest", line 5, in <module>
    from unstructured.ingest.main import main
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/main.py", line 2, in <module>
    from unstructured.ingest.cli.cli import get_cmd
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/cli/__init__.py", line 5, in <module>
    from unstructured.ingest.cli.cmds import base_dest_cmd_fns, base_src_cmd_fns
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/cli/cmds/__init__.py", line 6, in <module>
    from unstructured.ingest.cli.base.src import BaseSrcCmd
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/cli/base/src.py", line 14, in <module>
    from unstructured.ingest.runner import runner_map
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/runner/__init__.py", line 4, in <module>
    from .airtable import AirtableRunner
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/runner/airtable.py", line 6, in <module>
    from unstructured.ingest.runner.base_runner import Runner
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/runner/base_runner.py", line 17, in <module>
    from unstructured.ingest.processor import process_documents
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/processor.py", line 15, in <module>
    from unstructured.ingest.pipeline import (
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/pipeline/__init__.py", line 3, in <module>
    from .partition import Partitioner
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/pipeline/partition.py", line 8, in <module>
    from unstructured.ingest.connector.registry import create_ingest_doc_from_dict
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/connector/registry.py", line 21, in <module>
    from unstructured.ingest.connector.notion.connector import (
  File "/Users/cragwolfe/.pyenv/versions/3.8.17/envs/unstlib/lib/python3.8/site-packages/unstructured/ingest/connector/notion/connector.py", line 6, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by ShubhamMishra2202** [comment]
! pip install httpx ---> may be this can fix the problem ...try this
