### ISSUE TITLE
bug/docx AttributeError: '_Header' object has no attribute 'iter_inner_content'

### ISSUE THREAD

**Issue by Klaijan** [Unstructured-IO/unstructured#2176]
**Describe the bug**
Unable to partition a `docx` file.

**To Reproduce**
```
elements_to_json(partition(filename="example-docs/handbook-1p.docx"), "example-docs/test_evaluate_files/unstructured_output/handbook-1p.docx.json")
```

**Expected behavior**

**Screenshots**
I ran
```
elements_to_json(partition(filename="example-docs/handbook-1p.docx"), "example-docs/test_evaluate_files/unstructured_output/handbook-1p.docx.json")```
```
And the error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/auto.py", line 283, in partition
    elements = _partition_docx(
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/documents/elements.py", line 503, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/file_utils/filetype.py", line 591, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/file_utils/filetype.py", line 546, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/chunking/title.py", line 241, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 228, in partition_docx
    return list(elements)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/lang.py", line 353, in apply_lang_metadata
    elements = list(elements)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 299, in _iter_document_elements
    yield from self._iter_section_headers(section)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 613, in _iter_section_headers
    yield from maybe_iter_header(section.header, "primary")
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 600, in maybe_iter_header
    text = self._header_footer_text(header)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 484, in _header_footer_text
    return "\n".join(text for text in iter_hdrftr_texts(hdrftr) if text)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 484, in <genexpr>
    return "\n".join(text for text in iter_hdrftr_texts(hdrftr) if text)
  File "/Users/klaijan/unstructuredio/unstructured/unstructured/partition/docx.py", line 475, in iter_hdrftr_texts
    for block_item in hdrftr.iter_inner_content():
AttributeError: '_Header' object has no attribute 'iter_inner_content'
```

**Environment Info**
```
OS version:  macOS-13.4-arm64-arm-64bit
Python version:  3.8.15
unstructured version:  0.11.1
unstructured-inference version:  0.7.10
pytesseract version:  0.3.10
Torch version:  2.1.0
Detectron2 is not installed

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.2
```

**Additional context**
[handbook-1p.docx](https://github.com/Unstructured-IO/unstructured/files/13492351/handbook-1p.docx)

**Comment by cragwolfe** [comment]
CC @scanny

**Comment by scanny** [comment]
@Klaijan check your `python-docx` version, needs to be latest (v1.1.0).

**Comment by scanny** [comment]
Closing this as assumed fixed by the version upgrade, but @Klaijan feel free to reopen if it's still giving a problem :)
