### ISSUE TITLE
bug: parition_docx complaint when there shouldn't be one

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#2183]
**Describe the bug**
Attempting to partition a pdf with a python env that only includes the `pdf` extra results in an error.

Mentioned in: https://github.com/langchain-ai/langchain/pull/13614#discussion_r1399556745

**To Reproduce**

in a fresh pyenv:

```
pip install unstructured[pdf]
```
then attempt to partition a .pdf file:

```
from unstructured.partition.auto import partition
from unstructured.__version__ import __version__
print(f"unstructured version: {__version__}")
partition(filename=<path-to-pdf-file>, strategy="hi_res")
```

witness:

$ python test-partition-simple.py
unstructured version: 0.11.0
Traceback (most recent call last):
  File "test-partition-simple.py", line 20, in <module>
    elements = partition(filename=filename, strategy=strategy)
  File "/Users/cragwolfe/.pyenv/versions/tmp22/lib/python3.8/site-packages/unstructured/partition/auto.py", line 282, in partition
    _partition_docx = _get_partition_with_extras("docx")
  File "/Users/cragwolfe/.pyenv/versions/tmp22/lib/python3.8/site-packages/unstructured/partition/auto.py", line 114, in _get_partition_with_extras
    raise ImportError(
ImportError: partition_docx is not available. Install the docx dependencies with pip install "unstructured[docx]"

**Expected behavior**
The pdf file is partitioned

**Environment Info**
macos. python3.8. unstructured==0.11.0.

**Comment by cragwolfe** [comment]
haha, in my test code above that error occurred with a .docx filename passed to `partition()`, as it should. for a .pdf, there was no error.
