### ISSUE TITLE
bug/ RuntimeError: object has no attribute nms:

### ISSUE THREAD

**Issue by ybsun0215** [Unstructured-IO/unstructured#2494]
**Describe the bug**
When I run the code to verify the installation, I get an error.

Code:
from unstructured.partition.pdf import partition_pdf
partition_pdf("example-docs/layout-parser-paper-fast.pdf", url=None)

D:\Tool\Conda\envs\unstructured\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] 。'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "E:\Python Project\unstructured-main\Testing.py", line 3, in <module>
    from unstructured.partition.pdf import partition_pdf
  File "E:\Python Project\unstructured-main\unstructured\partition\pdf.py", line 99, in <module>
    from unstructured.partition.utils.processing_elements import clean_pdfminer_inner_elements
  File "E:\Python Project\unstructured-main\unstructured\partition\utils\processing_elements.py", line 3, in <module>
    from unstructured_inference.inference.layout import DocumentLayout
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\unstructured_inference\inference\layout.py", line 20, in <module>
    from unstructured_inference.models.base import get_model
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\unstructured_inference\models\base.py", line 7, in <module>
    from unstructured_inference.models.detectron2 import (
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\unstructured_inference\models\detectron2.py", line 5, in <module>
    from layoutparser.models.detectron2.layoutmodel import (
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\layoutparser\models\__init__.py", line 17, in <module>
    from .effdet.layoutmodel import EfficientDetLayoutModel
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\layoutparser\models\effdet\__init__.py", line 16, in <module>
    from .layoutmodel import EfficientDetLayoutModel
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 28, in <module>
    from effdet import create_model
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\effdet\__init__.py", line 2, in <module>
    from .bench import DetBenchPredict, DetBenchTrain, unwrap_bench
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\effdet\bench.py", line 70, in <module>
    def _batch_detection(
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_script.py", line 1381, in script
    fn = torch._C._jit_script_compile(
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_recursive.py", line 1010, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_script.py", line 1381, in script
    fn = torch._C._jit_script_compile(
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_recursive.py", line 1010, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_script.py", line 1381, in script
    fn = torch._C._jit_script_compile(
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_recursive.py", line 1010, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_script.py", line 1381, in script
    fn = torch._C._jit_script_compile(
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_recursive.py", line 1010, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torch\jit\_script.py", line 1381, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
object has no attribute nms:
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torchvision\ops\boxes.py", line 41
        _log_api_usage_once(nms)
    _assert_has_ops()
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
'nms' is being compiled since it was called from '_batched_nms_vanilla'
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torchvision\ops\boxes.py", line 109
    for class_id in torch.unique(idxs):
        curr_indices = torch.where(idxs == class_id)[0]
        curr_keep_indices = nms(boxes[curr_indices], scores[curr_indices], iou_threshold)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        keep_mask[curr_indices[curr_keep_indices]] = True
    keep_indices = torch.where(keep_mask)[0]
'_batched_nms_vanilla' is being compiled since it was called from 'batched_nms'
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\torchvision\ops\boxes.py", line 73
    # https://github.com/pytorch/vision/issues/1311#issuecomment-781329339
    if boxes.numel() > (4000 if boxes.device.type == "cpu" else 20000) and not torchvision._is_tracing():
        return _batched_nms_vanilla(boxes, scores, idxs, iou_threshold)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return _batched_nms_coordinate_trick(boxes, scores, idxs, iou_threshold)
'batched_nms' is being compiled since it was called from 'generate_detections'
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\effdet\anchors.py", line 140
        scores[top_detection_idx] = soft_scores
    else:
        top_detection_idx = batched_nms(boxes, scores, classes, iou_threshold=0.5)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

    # keep only top max_det_per_image scoring predictions
'generate_detections' is being compiled since it was called from '_batch_detection'
  File "D:\Tool\Conda\envs\unstructured\lib\site-packages\effdet\bench.py", line 82
        img_scale_i = None if img_scale is None else img_scale[i]
        img_size_i = None if img_size is None else img_size[i]
        detections = generate_detections(
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            class_out[i],
            ~~~~~~~~~~~~~
            box_out[i],
            ~~~~~~~~~~~
            anchor_boxes,
            ~~~~~~~~~~~~~
            indices[i],
            ~~~~~~~~~~~
            classes[i],
            ~~~~~~~~~~~
            img_scale_i,
            ~~~~~~~~~~~~
            img_size_i,
            ~~~~~~~~~~~
            max_det_per_image=max_det_per_image,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            soft_nms=soft_nms,
            ~~~~~~~~~~~~~~~~~ <--- HERE
        )
        batch_detections.append(detections)
**To Reproduce**
Provide a code snippet that reproduces the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/48913347/4a626a31-a14d-4c3a-ad2e-689babc6e800)
![image](https://github.com/Unstructured-IO/unstructured/assets/48913347/206ba9ea-13cf-4ca4-bdfd-dcea9d0d3575)


**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by timorobin** [comment]
I had a similar issue out of blue and was able to fix it  by pinning torchvision to be `~0.16`. It only happened on pdf's that were pure tables, like an excel file. My error message was a bit different though, so I'll paste it below. Hope this helps!

```Traceback (most recent call last):
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/timorobin/.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 48, in <module>
    from timm import create_model
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/timm/__init__.py", line 2, in <module>
    from .layers import is_scriptable, is_exportable, set_scriptable, set_exportable
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/timm/layers/__init__.py", line 7, in <module>
    from .classifier import ClassifierHead, create_classifier, NormMlpClassifierHead
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/timm/layers/classifier.py", line 15, in <module>
    from .create_norm import get_norm_layer
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/timm/layers/create_norm.py", line 14, in <module>
    from torchvision.ops.misc import FrozenBatchNorm2d
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/torchvision/_meta_registrations.py", line 26, in <module>
    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):
  File "/home/timorobin/.cache/pypoetry/virtualenvs/seraph-bDWL-skC-py3.9/lib/python3.9/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
```

**Comment by ybsun0215** [comment]
I apologize, I didn't fundamentally address the issue. I successfully configured it after switching from Windows to Linux system.

**Comment by AntoninLeroy** [comment]
I have the same issue. not clear on what to do to fix it.
I'm already on ubuntu.
