### ISSUE TITLE
bug/pip dependency broken for detectron2 and iopath

### ISSUE THREAD

**Issue by cooknl** [Unstructured-IO/unstructured#2694]
**Describe the bug**

Installing on Windows for local inference following https://unstructured-io.github.io/unstructured/installation/full_installation.html ot the 

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> detectron2 0.5 requires iopath<0.1.10,>=0.1.7, but you have iopath 0.1.10 which is incompatible.

**To Reproduce**
`pip install unstructured[local-inference]`

**Expected behavior**
No pip install issue

**Screenshots**
Not required

**Environment Info**
collect_env.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
OS version:  Windows-10-10.0.22631-SP0
Python version:  3.10.13
unstructured version:  0.12.6
unstructured-inference version:  0.7.23
pytesseract version:  0.3.10
Torch version:  2.2.0
Detectron2 version:  0.5
PaddleOCR is not installed
Traceback (most recent call last):
  File "C:\Users\natha\unstructured\scripts\collect_env.py", line 242, in <module>
    main()
  File "C:\Users\natha\unstructured\scripts\collect_env.py", line 224, in main
    libmagic_version = get_libmagic_version()
  File "C:\Users\natha\unstructured\scripts\collect_env.py", line 146, in get_libmagic_version
    result = subprocess.run(
  File "C:\Users\natha\anaconda3\envs\unstructured\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\natha\anaconda3\envs\unstructured\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\natha\anaconda3\envs\unstructured\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Additional context**

**Comment by MthwRobinson** [comment]
Closing, we've dropped support for the original `detectron2` model in favor of the ONNX version
