### ISSUE TITLE
bug/missing english_words.txt in PyPi release 0.13.1

### ISSUE THREAD

**Issue by rskew** [Unstructured-IO/unstructured#2855]
**Describe the bug**
PyPi release 0.13.1 is missing the file `unstructured/nlp/english-words.txt` causing it to crash

**To Reproduce**
```
$ python -m venv venv
$ source venv/bin/activate
$ pip install unstructured==0.13.1
$ python -c "from unstructured.partition import text_type"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rowan/demo/venv/lib/python3.11/site-packages/unstructured/nlp/english_words.py", line 12, in <module>
    with open(ENGLISH_WORDS_FILE) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/rowan/demo/venv/lib/python3.11/site-packages/unstructured/nlp/english-words.txt'
```

**Expected behavior**
Doesn't crash

**Screenshots**

**Environment Info**
```
$ python scripts/collect_env.py
OS version:  Linux-6.1.64-x86_64-with-glibc2.38
Python version:  3.11.6
unstructured version:  0.13.1
unstructured-inference is not installed
pytesseract is not installed
Torch is not installed
Detectron2 is not installed

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
PaddleOCR is not installed
Libmagic version: file-5.45
magic file from /nix/store/4if234lnkhfkindsr9m62s4b4lh3iynf-file-5.45/share/misc/magic
LibreOffice version:  LibreOffice 7.5.7.1 50(Build:1)
```

**Additional context**

**Comment by meet5398** [comment]
missing english_words.txt file  from last 3 hrs
![image](https://github.com/Unstructured-IO/unstructured/assets/108387640/1e86d187-49e7-4cd9-bb4c-b73b9d21a7e3)

**Comment by sidfinster** [comment]
Thanks for the prompt fix, came here to file a bug as well!

**Comment by cragwolfe** [comment]
Confirmed that 

```
python -c "from unstructured.partition import text_type"
```
works now in 0.13.2. i was also able to repro the issue in 0.13.1. Thanks for reporting @rskew !
