### ISSUE TITLE
Fallback for PDF to image if `poppler` is not available

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#310]
Currently the [`unstructured-inference`](https://github.com/Unstructured-IO/unstructured-inference) library relies on [`poppler`](https://github.com/freedesktop/poppler) for converting PDFs to images. The goal of this issue is to have a fallback to enable `unstructured-inference` to still convert PDFs to images if `poppler` isn't available. [`PyMuPDF`](https://github.com/pymupdf/PyMuPDF) appears to support converting PDFs to images without any system dependencies. See [this StackOverflow post](https://stackoverflow.com/questions/69643954/converting-pdf-to-png-with-python-without-pdf2image) for some example usage patterns.

**Comment by HAKSOAT** [comment]
Hi @MthwRobinson I worked on this fallback task in a [PR](https://github.com/Unstructured-IO/unstructured-inference/pull/70).

**Comment by MthwRobinson** [comment]
Thanks @HAKSOAT !

**Comment by NotBrianZach** [comment]
I think poppler is also gpl so not sure if that affects licensing

**Comment by cragwolfe** [comment]
Hi @NotBrianZach , you may find https://github.com/Belval/pdf2image/issues/124 to be a useful reference.

**Comment by ArkFreestyle** [comment]
I don't think the fallback is working anymore with unstructured version==0.13.7

I'm getting the exception:
```
  File "<install-path>\Python\Python311\site-packages\unstructured\partition\auto.py", line 426, in partition
    elements = _partition_pdf(
               ^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\documents\elements.py", line 570, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\file_utils\filetype.py", line 622, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\file_utils\filetype.py", line 582, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\chunking\dispatch.py", line 83, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\partition\pdf.py", line 201, in partition_pdf
    return partition_pdf_or_image(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\partition\pdf.py", line 292, in partition_pdf_or_image
    elements = _partition_pdf_or_image_local(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\utils.py", line 230, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured\partition\pdf.py", line 422, in _partition_pdf_or_image_local
    inferred_document_layout = process_file_with_model(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured_inference\inference\layout.py", line 396, in process_file_with_model
    else DocumentLayout.from_file(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured_inference\inference\layout.py", line 64, in from_file
    _image_paths = convert_pdf_to_image(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python\Python311\site-packages\unstructured_inference\inference\layout.py", line 433, in convert_pdf_to_image
    images = pdf2image.convert_from_path(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python311\Lib\site-packages\pdf2image\pdf2image.py", line 127, in convert_from_path
    page_count = pdfinfo_from_path(
                 ^^^^^^^^^^^^^^^^^^
  File "<install-path>\Python311\Lib\site-packages\pdf2image\pdf2image.py", line 594, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

When I downgrade unstructured to version==0.12.6, this does not happen. 

Shall we reopen this issue?

**Comment by MthwRobinson** [comment]
Hey @ArkFreestyle - yeah I think what you described makes sense as it's own issue. If you open a bug report for that behave and tag me + @christinestraub , we can take a look.

**Comment by ArkFreestyle** [comment]
Sorry, I was going to open a bug report but then I realized I was unable reproduce the problem without langchain, especially if I called unstructured's functions directly.  The traceback above is a little misleading because it's not the full traceback, here's the FULL traceback, in case it someone else sees this:

```
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\pdf2image\pdf2image.py", line 581, in pdfinfo_from_path
    proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path-to-my-code>.py", line 67, in __create_document_knowledge_base
    knowledge_base_service.create(directory, chunk_size, chunk_overlap)
  File "<path-to-my-code>.py", line 93, in create
    split_documents = self.__retrieve_split_documents(directory, chunk_size, chunk_overlap)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path-to-my-code>.py", line 172, in __retrieve_split_documents
    return self.directory_loader.load_and_split(text_splitter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\langchain_core\document_loaders\base.py", line 63, in load_and_split
    docs = self.load()
           ^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\langchain_community\document_loaders\azure_blob_storage_container.py", line 44, in load
    docs.extend(loader.load())
                ^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\langchain_community\document_loaders\azure_blob_storage_file.py", line 44, in load
    return loader.load()
           ^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\langchain_core\document_loaders\base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\langchain_community\document_loaders\unstructured.py", line 88, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\langchain_community\document_loaders\unstructured.py", line 180, in _get_elements
    return partition(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\partition\auto.py", line 426, in partition
    elements = _partition_pdf(
               ^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\documents\elements.py", line 570, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\file_utils\filetype.py", line 622, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\file_utils\filetype.py", line 582, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\chunking\dispatch.py", line 83, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\partition\pdf.py", line 201, in partition_pdf
    return partition_pdf_or_image(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\partition\pdf.py", line 292, in partition_pdf_or_image
    elements = _partition_pdf_or_image_local(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\utils.py", line 230, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured\partition\pdf.py", line 422, in _partition_pdf_or_image_local
    inferred_document_layout = process_file_with_model(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured_inference\inference\layout.py", line 394, in process_file_with_model
    else DocumentLayout.from_file(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured_inference\inference\layout.py", line 64, in from_file
    _image_paths = convert_pdf_to_image(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\unstructured_inference\inference\layout.py", line 431, in convert_pdf_to_image
    images = pdf2image.convert_from_path(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\pdf2image\pdf2image.py", line 127, in convert_from_path
    page_count = pdfinfo_from_path(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Roaming\Python\Python311\site-packages\pdf2image\pdf2image.py", line 607, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

I guess it might be an edge case that happens due to the way langchain calls unstructured's functions, it certainly doesn't happen in the normal case when I open the same pdf using unstructured:

```
from unstructured.partition.pdf import partition_pdf, partition_pdf_or_image


elements = partition_pdf(filename="my-file.pdf")
print("elements:", elements)

elements2 = partition_pdf_or_image(filename="my-file.pdf")
print("elements2:", elements2)
```

I tried to trace the code flow to figure out where exactly it starts, but unfortunately langchain's codebase is too abstracted for me to be able to identify the exact issue without spending hours on it... maybe this needs to be opened as an issue for langchain-community instead of unstructured. And I have no idea what that first exception is, even the traceback for that is too short. If it rings any bells for you, let me know.

Regardless, thank you for your time and a very swift response!

**Comment by ArkFreestyle** [comment]
Whoa, so this is no longer happening with unstructured==0.14.0 😮 
Maybe ya'll fixed it already 🎉

**Comment by MthwRobinson** [comment]
Wow! Glad it's fixed 🎉 . Thanks for following up @ArkFreestyle !

**Comment by lsorber** [comment]
Unstructured v0.14.3 fails with an error saying that `poppler` is not available on this simple example:
```python
from unstructured.partition.pdf import partition_pdf

elements = partition_pdf(filename="example.pdf", infer_table_structure=True, strategy="hi_res")
```
Output:
```
PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

**Comment by MthwRobinson** [comment]
Closing this issue. We didn't move forward with it because PyMuPDF is GPL licensed.

**Comment by lsorber** [comment]
@MthwRobinson I suppose you mean Poppler is GPL licensed? PyMuPDF could be a fallback for Poppler, but it’s also GPL licensed.

Should I open a new issue for the basic example that fails above? I understand if neither Poppler nor PyMuPDF are desirable, but the result is that partitioning a pdf fails out of the box.

**Comment by MthwRobinson** [comment]
Does the code work for you if you have Poppler installed? 

Poppler is also GPL licensed, but falls into a different category for us since it's a system dependency and not a Python package. We avoid GPL licensed Python dependencies are generally fine with bindings to GPL licensed system dependencies.
