### ISSUE TITLE
bug/ Resource punkt_tab not found

### ISSUE THREAD

**Issue by Wendong-Fan** [Unstructured-IO/unstructured#3519]
**Describe the bug**
```
Traceback (most recent call last):
  File "/Users/enrei/Desktop/camel_debug/camel/camel/loaders/tt.py", line 7, in <module>
    elements = partition_html(url="https://www.cnn.com/2023/01/30/sport/empire-state-building-green-philadelphia-eagles-spt-intl/index.html")
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/documents/elements.py", line 371, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 591, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 546, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/chunking/title.py", line 297, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/partition/html.py", line 141, in partition_html
    document_to_element_list(
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/partition/common.py", line 561, in document_to_element_list
    num_pages = len(document.pages)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/documents/xml.py", line 53, in pages
    self._pages = self._read()
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/documents/html.py", line 146, in _read
    element = _parse_tag(tag_elem)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/documents/html.py", line 321, in _parse_tag
    return _text_to_element(
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/documents/html.py", line 370, in _text_to_element
    elif is_narrative_tag(text, tag):
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/documents/html.py", line 417, in is_narrative_tag
    return tag not in HEADING_TAGS and is_possible_narrative_text(text)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/partition/text_type.py", line 77, in is_possible_narrative_text
    if exceeds_cap_ratio(text, threshold=cap_threshold):
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/partition/text_type.py", line 273, in exceeds_cap_ratio
    if sentence_count(text, 3) > 1:
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/partition/text_type.py", line 222, in sentence_count
    sentences = sent_tokenize(text)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/unstructured/nlp/tokenize.py", line 30, in sent_tokenize
    return _sent_tokenize(text)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = PunktTokenizer(language)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__
    self.load_lang(lang)
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
  File "/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/python3.10/site-packages/nltk/data.py", line 582, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/Users/enrei/nltk_data'
    - '/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/nltk_data'
    - '/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/share/nltk_data'
    - '/Users/enrei/Library/Caches/pypoetry/virtualenvs/camel-ai-QAH_KI_X-py3.10/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**To Reproduce**
```
from unstructured.partition.html import partition_html

elements = partition_html(url="https://www.cnn.com/2023/01/30/sport/empire-state-building-green-philadelphia-eagles-spt-intl/index.html")

for element in elements:
    print(element)

```
**Expected behavior**

should be able to partition the url

**Screenshots**

<img width="864" alt="Screenshot 2024-08-14 at 17 54 53" src="https://github.com/user-attachments/assets/715b1300-f360-4f16-b80e-ac2322a89579">

**Environment Info**

Python 3.10.9 (main, Mar  1 2023, 12:33:47) [Clang 14.0.6 ]

name = "unstructured"
version = "0.10.30"

**Additional context**

**Comment by PhorstenkampFuzzy** [comment]
I think this happens again. NLTK build a new version that has the same problem.

**Comment by will-mako-ai** [comment]
take a look here & try upgrading to `0.15.5`: https://github.com/Unstructured-IO/unstructured/issues/3511

**Comment by Wendong-Fan** [comment]
Thanks @will-mako-ai !
