### ISSUE TITLE
bug/partiton docx with table fail

### ISSUE THREAD

**Issue by Klaijan** [Unstructured-IO/unstructured#3628]
**Describe the bug**
`partition` (auto to `docx`) cannot parse a docx file. It seems to fail when encounter a table.
```
>>> elements = partition(filename="example-docs/handbook-872p.docx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/auto.py", line 230, in partition
    elements = partition_docx(
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/documents/elements.py", line 605, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 731, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 687, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/chunking/dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/docx.py", line 179, in partition_docx
    return list(elements)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/lang.py", line 475, in apply_lang_metadata
    elements = list(elements)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/docx.py", line 435, in _iter_document_elements
    yield from self._iter_table_element(block_item)
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/docx.py", line 778, in _iter_table_element
    self._convert_table_to_html(table) if self._opts.infer_table_structure else None
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/docx.py", line 553, in _convert_table_to_html
    return htmlify_matrix_of_cell_texts([list(iter_row_cells_as_text(r)) for r in table.rows])
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/docx.py", line 553, in <listcomp>
    return htmlify_matrix_of_cell_texts([list(iter_row_cells_as_text(r)) for r in table.rows])
  File "/Users/klaijan/.pyenv/versions/unstructured-all/lib/python3.10/site-packages/unstructured/partition/docx.py", line 542, in iter_row_cells_as_text
    for _ in range(row.grid_cols_before):
AttributeError: '_Row' object has no attribute 'grid_cols_before'
```

**To Reproduce**
```
from unstructured.partition.auto import partition
elements = partition(filename="example-docs/handbook-872p.docx")
```

**Expected behavior**

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
Fwiw this is my `unstructured` libs
unstructured==0.15.12
unstructured-client==0.25.8
unstructured-inference==0.7.36
unstructured-ingest==0.0.13
unstructured.pytesseract==0.3.12

**Additional context**

**Comment by Klaijan** [comment]
[handbook-872p.docx](https://github.com/user-attachments/files/16998799/handbook-872p.docx)

**Comment by scanny** [comment]
@Klaijan Try updating your `python-docx` installation:
```bash
$ pip install -U python-docx
```
That feature was added relatively recently, although some months ago now.
