### ISSUE TITLE
bug/Extract ppt failed by api 

### ISSUE THREAD

**Issue by JohnJyong** [Unstructured-IO/unstructured#3707]
**Describe the bug**
When I pulled the latest image of `downloads.unstructured.io/unstructured-io/unstructured-api` and  extract a ppt file , by `partition_via_api` , it is failed, i have attached the logs .
But is is fine in the docker image id: `8e76c3411895`

**To Reproduce**
Provide a code snippet that reproduces the issue.

**Expected behavior**

**Screenshots**

**Environment Info**
the codes below:

```
        from unstructured.partition.api import partition_via_api

        elements = partition_via_api(filename=self._file_path, api_url=self._api_url, api_key=self._api_key)
        text_by_page = {}
        for element in elements:
            page = element.metadata.page_number
            text = element.text
            if page in text_by_page:
                text_by_page[page] += "\n" + text
            else:
                text_by_page[page] = text

        combined_texts = list(text_by_page.values())
```

**Additional context**
error logs below :

```
2024-10-09 08:42:12,823 unstructured_api DEBUG partition input data: {"content_type": "application/vnd.ms-excel", "strategy": "auto", "ocr_languages": null, "coordinates": false, "pdf_infer_table_structure": true, "include_page_breaks": false, "encoding": "utf-8", "hi_res_model_name": null, "xml_keep_tags": false, "skip_infer_table_types": [], "languages": null, "chunking_strategy": null, "multipage_sections": true, "combine_under_n_chars": null, "new_after_n_chars": null, "max_characters": 500, "overlap": 0, "overlap_all": false, "extract_image_block_types": null, "extract_image_block_to_payload": false, "unique_element_ids": false, "include_slide_notes": true}
2024-10-09 08:42:12,823 unstructured WARNING The pdf_infer_table_structure kwarg is deprecated. Please use skip_infer_table_types instead.
2024-10-09 08:42:12,826 10.10.17.48:45502 POST /general/v0/general HTTP/1.1 - 500 Internal Server Error
2024-10-09 08:42:12,827 uvicorn.error ERROR Exception in ASGI application
Traceback (most recent call last):
  File "/home/notebook-user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
2024-10-09T08:42:12.830620862Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830624681Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-10-09T08:42:12.830626979Z     return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830632384Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
2024-10-09T08:42:12.830637199Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-10-09T08:42:12.830639463Z     await self.middleware_stack(scope, receive, send)
2024-10-09T08:42:12.830641623Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-10-09T08:42:12.830644003Z     raise exc
2024-10-09T08:42:12.830651966Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-10-09T08:42:12.830654603Z     await self.app(scope, receive, _send)
2024-10-09T08:42:12.830666531Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-10-09T08:42:12.830669222Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-09T08:42:12.830671554Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-10-09T08:42:12.830673645Z     raise exc
2024-10-09T08:42:12.830675633Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-10-09T08:42:12.830677707Z     await app(scope, receive, sender)
2024-10-09T08:42:12.830679729Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 754, in __call__
2024-10-09T08:42:12.830681992Z     await self.middleware_stack(scope, receive, send)
2024-10-09T08:42:12.830684634Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 774, in app
2024-10-09T08:42:12.830687027Z     await route.handle(scope, receive, send)
2024-10-09T08:42:12.830689300Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 295, in handle
2024-10-09T08:42:12.830691878Z     await self.app(scope, receive,
 send)
2024-10-09T08:42:12.830694265Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-10-09T08:42:12.830696472Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-09T08:42:12.830698727Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-10-09T08:42:12.830701090Z     raise exc
2024-10-09T08:42:12.830703762Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-10-09T08:42:12.830706150Z     await app(scope, receive, sender)
2024-10-09T08:42:12.830708630Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
2024-10-09T08:42:12.830711482Z     response = await f(request)
2024-10-09T08:42:12.830713605Z                ^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830715962Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-10-09T08:42:12.830717991Z     raw_response = await run_endpoint_function(
2024-10-09T08:42:12.830720374Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-10-09T08:42:12.830725084Z     return await run_in_threadpool(dependant.call, **values)
2024-10-09T08:42:12.830728143Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830730501Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-10-09T08:42:12.830732754Z     return await anyio.to_thread.run_sync(func, *args)
2024-10-09T08:42:12.830736350Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830738894Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-10-09T08:42:12.830741380Z     return await get_async_backend().run_sync_in_worker_thread(
2024-10-09T08:42:12.830743836Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830746780Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-10-09T08:42:12.830752602Z     return await future
2024-10-09T08:42:12.830754938Z            ^^^^^^^^^^^^
2024-10-09T08:42:12.830757256Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-10-09T08:42:12.830759656Z     result = context.run(func, *args)
2024-10-09T08:42:12.830761885Z              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830770050Z   File "/home/notebook-user/prepline_general/api/general.py", line 793, in general_partition
2024-10-09T08:42:12.830772554Z     list(response_generator(is_multipart=False))[0]
2024-10-09T08:42:12.830775070Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830777865Z   File "/home/notebook-user/prepline_general/api/general.py", line 727, in response_generator
2024-10-09T08:42:12.830780248Z     response = pipeline_api(
2024-10-09T08:42:12.830782332Z     
           ^^^^^^^^^^^^^
2024-10-09T08:42:12.830784823Z   File "/home/notebook-user/prepline_general/api/general.py", line 424, in pipeline_api
2024-10-09T08:42:12.830787290Z     elements = partition(**partition_kwargs)  # type: ignore # pyright: ignore[reportGeneralTypeIssues]
2024-10-09T08:42:12.830789634Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830792022Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/auto.py", line 426, in partition
2024-10-09T08:42:12.830794336Z     elements = partition_xlsx(
2024-10-09T08:42:12.830796632Z                ^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830799161Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/documents/elements.py", line 605, in wrapper
2024-10-09T08:42:12.830801410Z     elements = func(*args, **kwargs)
2024-10-09T08:42:12.830803590Z                ^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830805679Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 706, in wrapper
2024-10-09T08:42:12.830807847Z     elements = func(*args, **kwargs)
2024-10-09T08:42:12.830809989Z                ^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830812212Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 662, in wrapper
2024-10-09T08:42:12.830814478Z     elements = func(*args, **kwargs)
2024-10-09T08:42:12.830816898Z                ^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830819243Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/chunking/dispatch.py", line 74, in wrapper
2024-10-09T08:42:12.830821499Z     elements = func(*args, **kwargs)
2024-10-09T08:42:12.830823830Z                ^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830826097Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/xlsx.py", line 109, in partition_xlsx
2024-10-09T08:42:12.830828549Z     opts.sheets.items(), start=starting_page_number
2024-10-09T08:42:12.830
830485Z     ^^^^^^^^^^^
2024-10-09T08:42:12.830832957Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/utils.py", line 155, in __get__
2024-10-09T08:42:12.830835321Z     value = self._fget(obj)
2024-10-09T08:42:12.830837487Z             ^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830839692Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/xlsx.py", line 282, in sheets
2024-10-09T08:42:12.830841975Z     return pd.read_excel(f, sheet_name=None, header=self.header_row_idx)
2024-10-09T08:42:12.830844303Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830846425Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
2024-10-09T08:42:12.830850885Z     io = ExcelFile(
2024-10-09T08:42:12.830853310Z          ^^^^^^^^^^
2024-10-09T08:42:12.830855492Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1567, in __init__
2024-10-09T08:42:12.830857755Z     self._reader = self._engines[engine](
2024-10-09T08:42:12.830859910Z                    ^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830862231Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_xlrd.py", line 46, in __init__
2024-10-09T08:42:12.830864427Z     super().__init__(
2024-10-09T08:42:12.830866703Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 573, in __init__
2024-10-09T08:42:12.830868911Z     self.book = self.load_workbook(self.handles.handle, engine_kwargs)
2024-10-09T08:42:12.830871469Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_xlrd.py", line 63, in load_workbook
2024-10-09T08:42:12.830875698Z     return open_workbook(file_contents=data, **engine_kwargs)
2024-10-09T08:42:12.830877849Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830880222Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/xlrd/__init__.py", line 172, in open_workbook
2024-10-09T08:42:12.830882518Z     bk = open_workbook_xls(
2024-10-09T08:42:12.830884674Z          ^^^^^^^^^^^^^^^^^^
2024-10-09T08:42:12.830886843Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/xlrd/book.py", line 68, in open_workbook_xls
2024-10-09T08:42:12.830888914Z     bk.biff2_8_load(
2024-10-09T08:42:12.830891091Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/xlrd/book.py", line 645, in biff2_8_load
2024-10-09T08:42:12.830893241Z     raise XLRDError("Can't find workbook in OLE2 compound document")
xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document
```

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by lambda-science** [comment]
Same issue. Found a fix ? `Can't find workbook in OLE2 compound document`

**Comment by scanny** [comment]
@lambda-science what is the traceback you receive?

Also we're going to need the filename, at least the extension.

If it's `{something}.ppt` then also make sure you can open it with PowerPoint.

In @JohnJyong 's case the content-type that was given or inferred was `"content_type": "application/vnd.ms-excel"` which is likely related. So if you're specifying a content type then make sure it's `"application/vnd.ms-powerpoint"`.

Note also this error arises on "protected" `.xls` files, so if you get this error but the file is XLS and not PPT then you can try removing the protection.

**Comment by lambda-science** [comment]
> @lambda-science what is the traceback you receive?
> 
> Also we're going to need the filename, at least the extension.
> 
> If it's `{something}.ppt` then also make sure you can open it with PowerPoint.
> 
> In @JohnJyong 's case the content-type that was given or inferred was `"content_type": "application/vnd.ms-excel"` which is likely related. So if you're specifying a content type then make sure it's `"application/vnd.ms-powerpoint"`.
> 
> Note also this error arises on "protected" `.xls` files, so if you get this error but the file is XLS and not PPT then you can try removing the protection.

Hello Scanny,
I'm trying to process an email (.msg) format :)

Here is the complete trace:
```python
2024-11-12 13:13:46,884 unstructured_api DEBUG pipeline_api input params: {"filename": "/tmp/ec36_Formatage JSON et XML.msg", "response_type": "application/json", "coordinates": false, "encoding": "utf-8", "hi_res_model_name": null, "include_page_breaks": false, "ocr_languages": null, "pdf_infer_table_structure": true, "skip_infer_table_types": [], "strategy": "fast", "xml_keep_tags": false, "languages": ["eng", "fra"], "extract_image_block_types": null, "unique_element_ids": false, "chunking_strategy": "by_title", "combine_under_n_chars": 1000, "max_characters": 2000, "multipage_sections": true, "new_after_n_chars": 1500, "overlap": 0, "overlap_all": false, "starting_page_number": null, "include_slide_notes": true}
2024-11-12T13:13:46.885618081Z 2024-11-12 13:13:46,884 unstructured_api DEBUG filetype: application/x-ole-storage
2024-11-12T13:13:46.885632820Z 2024-11-12 13:13:46,885 unstructured_api DEBUG partition input data: {"content_type": "application/x-ole-storage", "strategy": "fast", "ocr_languages": null, "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": "utf-8", "hi_res_model_name": null, "xml_keep_tags": false, "skip_infer_table_types": [], "languages": ["eng", "fra"], "chunking_strategy": "by_title", "multipage_sections": true, "combine_under_n_chars": 1000, "new_after_n_chars": 1500, "max_characters": 2000, "overlap": 0, "overlap_all": false, "extract_image_block_types": null, "extract_image_block_to_payload": false, "unique_element_ids": false, "include_slide_notes": true}
2024-11-12T13:13:46.891335831Z 2024-11-12 13:13:46,890 172.18.0.3:57794 POST /general/v0/general HTTP/1.1 - 500 Internal Server Error
2024-11-12T13:13:46.897108341Z 2024-11-12 13:13:46,891 uvicorn.error ERROR Exception in ASGI application
2024-11-12T13:13:46.897220305Z Traceback (most recent call last):
2024-11-12T13:13:46.897238040Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
2024-11-12T13:13:46.897248812Z     result = await app(  # type: ignore[func-returns-value]
2024-11-12T13:13:46.897261026Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897274473Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-11-12T13:13:46.897282008Z     return await self.app(scope, receive, send)
2024-11-12T13:13:46.897288120Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897303020Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-11-12T13:13:46.897310365Z     await super().__call__(scope, receive, send)
2024-11-12T13:13:46.897316227Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-11-12T13:13:46.897322058Z     await self.middleware_stack(scope, receive, send)
2024-11-12T13:13:46.897327760Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-11-12T13:13:46.897334012Z     raise exc
2024-11-12T13:13:46.897339563Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-11-12T13:13:46.897346086Z     await self.app(scope, receive, _send)
2024-11-12T13:13:46.897351607Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-11-12T13:13:46.897357599Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-11-12T13:13:46.897363661Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-11-12T13:13:46.897369733Z     raise exc
2024-11-12T13:13:46.897375725Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-11-12T13:13:46.897382078Z     await app(scope, receive, sender)
2024-11-12T13:13:46.897395775Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 754, in __call__
2024-11-12T13:13:46.897403381Z     await self.middleware_stack(scope, receive, send)
2024-11-12T13:13:46.897409252Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 774, in app
2024-11-12T13:13:46.897415525Z     await route.handle(scope, receive, send)
2024-11-12T13:13:46.897424312Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 295, in handle
2024-11-12T13:13:46.897430665Z     await self.app(scope, receive, send)
2024-11-12T13:13:46.897443230Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-11-12T13:13:46.897474042Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-11-12T13:13:46.897485364Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-11-12T13:13:46.897492138Z     raise exc
2024-11-12T13:13:46.897497949Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-11-12T13:13:46.897504312Z     await app(scope, receive, sender)
2024-11-12T13:13:46.897510184Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
2024-11-12T13:13:46.897516677Z     response = await f(request)
2024-11-12T13:13:46.897522539Z                ^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897528601Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-11-12T13:13:46.897534983Z     raw_response = await run_endpoint_function(
2024-11-12T13:13:46.897540965Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897547048Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-11-12T13:13:46.897553300Z     return await run_in_threadpool(dependant.call, **values)
2024-11-12T13:13:46.897559352Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897565504Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-11-12T13:13:46.897571747Z     return await anyio.to_thread.run_sync(func, *args)
2024-11-12T13:13:46.897577909Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897583781Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-11-12T13:13:46.897590134Z     return await get_async_backend().run_sync_in_worker_thread(
2024-11-12T13:13:46.897596216Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897602288Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-11-12T13:13:46.897608971Z     return await future
2024-11-12T13:13:46.897615073Z            ^^^^^^^^^^^^
2024-11-12T13:13:46.897620765Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-11-12T13:13:46.897627328Z     result = context.run(func, *args)
2024-11-12T13:13:46.897633200Z              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897640143Z   File "/home/notebook-user/prepline_general/api/general.py", line 793, in general_partition
2024-11-12T13:13:46.897646586Z     list(response_generator(is_multipart=False))[0]
2024-11-12T13:13:46.897652749Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897668350Z   File "/home/notebook-user/prepline_general/api/general.py", line 727, in response_generator
2024-11-12T13:13:46.897674843Z     response = pipeline_api(
2024-11-12T13:13:46.897680805Z                ^^^^^^^^^^^^^
2024-11-12T13:13:46.897686907Z   File "/home/notebook-user/prepline_general/api/general.py", line 424, in pipeline_api
2024-11-12T13:13:46.897693290Z     elements = partition(**partition_kwargs)  # type: ignore # pyright: ignore[reportGeneralTypeIssues]
2024-11-12T13:13:46.897699732Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897705865Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/auto.py", line 426, in partition
2024-11-12T13:13:46.897712268Z     elements = partition_xlsx(
2024-11-12T13:13:46.897718189Z                ^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897724161Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/documents/elements.py", line 605, in wrapper
2024-11-12T13:13:46.897730614Z     elements = func(*args, **kwargs)
2024-11-12T13:13:46.897736446Z                ^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897742538Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 706, in wrapper
2024-11-12T13:13:46.897748831Z     elements = func(*args, **kwargs)
2024-11-12T13:13:46.897754762Z                ^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897760804Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 662, in wrapper
2024-11-12T13:13:46.897767137Z     elements = func(*args, **kwargs)
2024-11-12T13:13:46.897773089Z                ^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897778941Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/chunking/dispatch.py", line 74, in wrapper
2024-11-12T13:13:46.897785404Z     elements = func(*args, **kwargs)
2024-11-12T13:13:46.897791225Z                ^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897797117Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/xlsx.py", line 109, in partition_xlsx
2024-11-12T13:13:46.897803410Z     opts.sheets.items(), start=starting_page_number
2024-11-12T13:13:46.897809522Z     ^^^^^^^^^^^
2024-11-12T13:13:46.897815434Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/utils.py", line 155, in __get__
2024-11-12T13:13:46.897821686Z     value = self._fget(obj)
2024-11-12T13:13:46.897827618Z             ^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897833680Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/xlsx.py", line 282, in sheets
2024-11-12T13:13:46.897841896Z     return pd.read_excel(f, sheet_name=None, header=self.header_row_idx)
2024-11-12T13:13:46.897848480Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897862337Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
2024-11-12T13:13:46.897868610Z     io = ExcelFile(
2024-11-12T13:13:46.897874532Z          ^^^^^^^^^^
2024-11-12T13:13:46.897880353Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1567, in __init__
2024-11-12T13:13:46.897886776Z     self._reader = self._engines[engine](
2024-11-12T13:13:46.897893129Z                    ^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897899211Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_xlrd.py", line 46, in __init__
2024-11-12T13:13:46.897905664Z     super().__init__(
2024-11-12T13:13:46.897911626Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 573, in __init__
2024-11-12T13:13:46.897917958Z     self.book = self.load_workbook(self.handles.handle, engine_kwargs)
2024-11-12T13:13:46.897924091Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897930183Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/pandas/io/excel/_xlrd.py", line 63, in load_workbook
2024-11-12T13:13:46.897936535Z     return open_workbook(file_contents=data, **engine_kwargs)
2024-11-12T13:13:46.897942708Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897948770Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/xlrd/__init__.py", line 172, in open_workbook
2024-11-12T13:13:46.897954982Z     bk = open_workbook_xls(
2024-11-12T13:13:46.897960944Z          ^^^^^^^^^^^^^^^^^^
2024-11-12T13:13:46.897966896Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/xlrd/book.py", line 68, in open_workbook_xls
2024-11-12T13:13:46.897973159Z     bk.biff2_8_load(
2024-11-12T13:13:46.897979131Z   File "/home/notebook-user/.local/lib/python3.11/site-packages/xlrd/book.py", line 645, in biff2_8_load
2024-11-12T13:13:46.897985483Z     raise XLRDError("Can't find workbook in OLE2 compound document")
2024-11-12T13:13:46.897991956Z xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document
```

**Comment by scanny** [comment]
Closing as inactive. Assuming this is resolved by recent changes to filetype-detection.
