### ISSUE TITLE
How to support Chinese filename path

### ISSUE THREAD

**Issue by shangdev** [Unstructured-IO/unstructured#400]
```
from pathlib import Path
from llama_index import download_loader

UnstructuredReader = download_loader("UnstructuredReader")

loader = UnstructuredReader()
documents = loader.load_data(file=Path('./data/abc-页面.html'))
```

error thrown:

```
WARNING:unstructured:The MIME type of 'data\\BWK\\abc-页面.html' is "cannot open `data\\BWK\\WCPA156-\\346\\265\\213\\350\\257\\225\\345\\267\\245\\350\\243\\205.html' (No such file or directory)". This file type is not currently supported in unstructured.
Traceback (most recent call last):
  File "D:\www\llamaIndexDemo\demo2.py", line 7, in <module>
    documents = loader.load_data(file=Path('./data/BWK/abc-页面.html'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python311\Lib\site-packages\llama_index\readers\llamahub_modules/file/unstructured/base.py", line 36, in load_data
    elements = partition(str(file))
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python311\Lib\site-packages\unstructured\partition\auto.py", line 104, in partition
    raise ValueError(f"{msg}. The {filetype} file type is not supported in partition.")
ValueError: Invalid file data\BWK\abc-页面.html. The FileType.UNK file type is not supported in partition.
```

**Comment by cragwolfe** [comment]
Hmm, the following works for me on mac:
```
from pathlib import Path
from llama_index import download_loader

UnstructuredReader = download_loader("UnstructuredReader")

loader = UnstructuredReader()
documents = loader.load_data(file=Path('example-docs/fake-页面.html'))
print(documents[0].text)
```

where `example-docs/fake-页面.html` is a copy of https://github.com/Unstructured-IO/unstructured/blob/main/example-docs/fake-html.html 

I suspect the `str(filename)` [here](https://github.com/emptycrown/llama-hub/blob/e97bb81/loader_hub/file/unstructured/base.py#L36) is throwing it off in Windows given the `(No such file or directory)` message in the trace you posted.

**Comment by shangdev** [comment]
@cragwolfe Yes, This is the result of running under Windows.

**Comment by shangdev** [comment]
![image](https://user-images.githubusercontent.com/15621520/227815994-d789f9b2-7ab7-4cd6-8cc9-4a7b840e9d35.png)

**Comment by MthwRobinson** [comment]
Going to close this one out since we haven't been able to replicate. We can reopen it later if we need to. For Windows you may also need `path = Path('.\\data\\abc-页面.html')` (the double forward slashes instead of backslashes).
