### ISSUE TITLE
partition of eml file is throwing exception of zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by slavag** [Unstructured-IO/unstructured#628]
**Describe the bug**
partition of eml file is throwing exception of zipfile.BadZipFile: File is not a zip file

**To Reproduce**

from unstructured.partition.auto import partition
elements = partition(filename="/Downloads/Products.eml")

**Expected behavior**
parsing without exception

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - Python version 3.10.11

**Additional context**
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/privateGPT/testemail.py", line 1, in <module>
    from unstructured.partition.auto import partition
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/unstructured/partition/auto.py", line 9, in <module>
    from unstructured.partition.doc import partition_doc
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/unstructured/partition/doc.py", line 7, in <module>
    from unstructured.partition.docx import partition_docx
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/unstructured/partition/docx.py", line 25, in <module>
    from unstructured.partition.text_type import (
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/unstructured/partition/text_type.py", line 21, in <module>
    from unstructured.nlp.tokenize import pos_tag, sent_tokenize, word_tokenize
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/unstructured/nlp/tokenize.py", line 32, in <module>
    _download_nltk_package_if_not_present(package_name, package_category)
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/unstructured/nlp/tokenize.py", line 21, in _download_nltk_package_if_not_present
    nltk.find(f"{package_category}/{package_name}")
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/Users/slava/.pyenv/versions/3.10.11/lib/python3.10/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by Torenable** [comment]
I also run into this issue at version 0.7.8. Is there any suggestion? Thanks a lot!

**Comment by premkashyap-official** [comment]
Hi. I am getting the same issue. Is there any solution for this?

![image](https://github.com/user-attachments/assets/7f02806e-492a-4204-8d36-7ba2ef392e29)
