### ISSUE TITLE
how to get API_KEY ?

### ISSUE THREAD

**Issue by codeacme17** [Unstructured-IO/unstructured#637]
I'm using JS to call Unstructured REST API, but now I need to provide api key, I don't know where can I get this api key.
Sorry, I'm a beginner, hope you can give me an answer

**Comment by cragwolfe** [comment]
@codeacme17 , for now it is just ignored. You should be able to pass an empty string or `null` for the api key value. this will likely change in the future, but in that event we'll have clear instructions on how to get an API key.

**Comment by codeacme17** [comment]
ok, thx, But I got this error, when I don't pass API KEY.

```bash
file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/node_modules/.pnpm/langchain@0.0.75_@pinecone-database+pinecone@0.1.5_cheerio@1.0.0-rc.12_mammoth@1.5.1_pdf-parse@1.1.1_playwright@1.33.0/node_modules/langchain/dist/document_loaders/fs/unstructured.js:72
            throw new Error(`Failed to partition file ${this.filePath} with error ${response.status} and message ${await response.text()}`);
                  ^

Error: Failed to partition file /Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/sources/ads/test.html with error 404 and message {"detail":"API key is invalid, please provide a valid API key in the header."}
    at UnstructuredLoader._partition (file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/node_modules/.pnpm/langchain@0.0.75_@pinecone-database+pinecone@0.1.5_cheerio@1.0.0-rc.12_mammoth@1.5.1_pdf-parse@1.1.1_playwright@1.33.0/node_modules/langchain/dist/document_loaders/fs/unstructured.js:72:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UnstructuredLoader.load (file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/node_modules/.pnpm/langchain@0.0.75_@pinecone-database+pinecone@0.1.5_cheerio@1.0.0-rc.12_mammoth@1.5.1_pdf-parse@1.1.1_playwright@1.33.0/node_modules/langchain/dist/document_loaders/fs/unstructured.js:81:26)
    at async file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/src/utils/loaders.js:83:21
    at async Promise.all (index 0)
    at async filesLoader (file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/src/utils/loaders.js:62:3)
    at async Module.initFiles (file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/src/models/modules/file-model.js:17:16)
    at async file:///Users/codeacme17/1LLESTGROUP/Websits/talk-with-files/server/index.js:65:3
```

this is my code 

```js
const loader = new UnstructuredLoader(filePath)
rawDocs = await loader.load()
```

**Comment by cragwolfe** [comment]
OK, if the value passed for api key is not empty, there will be an error message refrom the API currently. From JS, try `null` as the value or empty string if that does not work.

Can you try https://js.langchain.com/docs/modules/indexes/document_loaders/examples/file_loaders/unstructured#usage

except with `set apiKey: "",`

**Comment by codeacme17** [comment]
its also not work...

```js
const options = {
  apiKey: '',
}

const loader = new UnstructuredLoader(filePath, options)

rawDocs = await loader.load()
```

**Comment by ericpullukaran** [comment]
I've tried the aforementioned `api_key=''` and I, too, am getting issues with this. Server Returning a 404

```
ValueError: Receive unexpected status code 404 from the API.
```

with details 

```
{'detail': 'API key is invalid, please provide a valid API key in the header.'}
```

**Comment by cragwolfe** [comment]
i've just updated the API so hopefully now you won't see errors with your original code.

**Comment by codeacme17** [comment]
yeah, thx, now its working~

**Comment by cragwolfe** [comment]
thanks for reporting!
