### ISSUE TITLE
Exception unknown encoding: iso-8859-8-i while parsing eml file.

### ISSUE THREAD

**Issue by slavag** [Unstructured-IO/unstructured#801]
**Describe the bug**
Exception unknown encoding: iso-8859-8-i while parsing eml file.

**To Reproduce**
Please use attached file (it's an eml renamed to txt)
[2022-08-31 075928 082a3a9bc6.txt](https://github.com/Unstructured-IO/unstructured/files/11846974/2022-08-31.075928.082a3a9bc6.txt)

**Expected behavior**
To not fail

**Desktop MacBook Pro M1:**
 - OS: MacOS 13.4
 - Browser : Chrome
 - Python version 3.11.3

**Additional context**
```
RemoteTraceback: 

Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 49, in load
    doc = UnstructuredEmailLoader.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 71, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/email.py", line 24, in _get_elements
    return partition_email(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/documents/elements.py", line 118, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 493, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/partition/email.py", line 307, in partition_email
    element.apply(_replace_mime_encodings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/documents/elements.py", line 312, in apply
    cleaned_text = cleaner(cleaned_text)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/cleaners/core.py", line 197, in replace_mime_encodings
    return quopri.decodestring(text.encode(encoding)).decode(encoding)
                               ^^^^^^^^^^^^^^^^^^^^^
LookupError: unknown encoding: iso-8859-8-i

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 89, in load_single_document
    return loader.load()
           ^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 59, in load
    raise type(e)(f"{self.file_path}: {e}") from e
LookupError: source_documents/2022-08-31 075928 082a3a9bc6.eml: unknown encoding: iso-8859-8-i
```

**Comment by MthwRobinson** [comment]
Thanks @slavag ! We'll take a look as a soon as we can. cc: @christinestraub
