### ISSUE TITLE
Exception on eml parsing.

### ISSUE THREAD

**Issue by slavag** [Unstructured-IO/unstructured#848]
**Describe the bug**
Parsing of the attached file (.eml renamed to .txt) throws an exception :
unknown encoding: "utf-8"content-transfer-encoding: 8bit

**To Reproduce**
Parse attached eml file
[2017-11-02 180015 cf4101f1b3.txt](https://github.com/Unstructured-IO/unstructured/files/11902539/2017-11-02.180015.cf4101f1b3.txt)

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Python version 3.11.3

Thanks.

**Additional context**
```
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 49, in load
    doc = UnstructuredEmailLoader.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 71, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/email.py", line 24, in _get_elements
    return partition_email(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/documents/elements.py", line 118, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 507, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/partition/email.py", line 311, in partition_email
    element.apply(_replace_mime_encodings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/documents/elements.py", line 312, in apply
    cleaned_text = cleaner(cleaned_text)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/cleaners/core.py", line 201, in replace_mime_encodings
    return quopri.decodestring(text.encode(formatted_encoding)).decode(formatted_encoding)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
LookupError: unknown encoding: "utf-8"content-transfer-encoding: 8bit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 89, in load_single_document
    return loader.load()
           ^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 59, in load
    raise type(e)(f"{self.file_path}: {e}") from e
LookupError: source_documents/2017-11-02 180015 cf4101f1b3.eml: unknown encoding: "utf-8"content-transfer-encoding: 8bit
"""

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/slava/Documents/Development/private/AI/privateGPT/ingest.py:166 in <module>               │
│                                                                                                  │
│   163                                                                                            │
│   164                                                                                            │
│   165 if __name__ == "__main__":                                                                 │
│ ❱ 166 │   main()                                                                                 │
│   167                                                                                            │
│                                                                                                  │
│ /Users/slava/Documents/Development/private/AI/privateGPT/ingest.py:150 in main                   │
│                                                                                                  │
│   147 │   │   print(f"Appending to existing vectorstore at {persist_directory}")                 │
│   148 │   │   db = Chroma(persist_directory=persist_directory, embedding_function=embeddings,    │
│   149 │   │   collection = db.get()                                                              │
│ ❱ 150 │   │   texts = process_documents([metadata['source'] for metadata in collection['metada   │
│   151 │   │   print(f"Creating embeddings. May take some minutes...")                            │
│   152 │   │   db.add_documents(texts)                                                            │
│   153 │   else:                                                                                  │
│                                                                                                  │
│ /Users/slava/Documents/Development/private/AI/privateGPT/ingest.py:118 in process_documents      │
│                                                                                                  │
│   115 │   Load documents and split in chunks                                                     │
│   116 │   """                                                                                    │
│   117 │   print(f"Loading documents from {source_directory}")                                    │
│ ❱ 118 │   documents = load_documents(source_directory, ignored_files)                            │
│   119 │   if not documents:                                                                      │
│   120 │   │   print("No new documents to load")                                                  │
│   121 │   │   exit(0)                                                                            │
│                                                                                                  │
│ /Users/slava/Documents/Development/private/AI/privateGPT/ingest.py:107 in load_documents         │
│                                                                                                  │
│   104 │   with Pool(processes=os.cpu_count()) as pool:                                           │
│   105 │   │   results = []                                                                       │
│   106 │   │   with tqdm(total=len(filtered_files), desc='Loading new documents', ncols=80) as    │
│ ❱ 107 │   │   │   for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_   │
│   108 │   │   │   │   results.extend(docs)                                                       │
│   109 │   │   │   │   pbar.update()                                                              │
│   110                                                                                            │
│                                                                                                  │
│ /Users/slava/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/pool.py:873 in next           │
│                                                                                                  │
│   870 │   │   success, value = item                                                              │
│   871 │   │   if success:                                                                        │
│   872 │   │   │   return value                                                                   │
│ ❱ 873 │   │   raise value                                                                        │
│   874 │                                                                                          │
│   875 │   __next__ = next                    # XXX                                               │
│   876                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
LookupError: source_documents/2017-11-02 180015 cf4101f1b3.eml: unknown encoding: "utf-8"content-transfer-encoding: 8bit
```

**Comment by MthwRobinson** [comment]
Yeah even if the header is malformed, it would be nice to handle this scenario. We'll take a look at this as soon as we can! cc: @mallorih @christinestraub
